set fallback := true
set shell := ["bash", "-uc"]
set ignore-comments

[no-cd]
cm msg:
  #!/usr/bin/env bash
  set -euo pipefail

  git add -A
  git commit -m "{{msg}}"

[no-cd]
push:
  #!/usr/bin/env bash
  set -euo pipefail

  git push
